// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameUser = "jsh_user"

// User 用户表
type User struct {
	ID           int64  `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键" json:"id"`                     // 主键
	Username     string `gorm:"column:username;not null;comment:用户姓名--例如张三" json:"username"`                      // 用户姓名--例如张三
	LoginName    string `gorm:"column:login_name;not null;comment:登录用户名" json:"loginName"`                        // 登录用户名
	Password     string `gorm:"column:password;comment:登陆密码" json:"password"`                                     // 登陆密码
	LeaderFlag   string `gorm:"column:leader_flag;comment:是否经理，0否，1是" json:"leaderFlag"`                          // 是否经理，0否，1是
	Position     string `gorm:"column:position;comment:职位" json:"position"`                                       // 职位
	Department   string `gorm:"column:department;comment:所属部门" json:"department"`                                 // 所属部门
	Email        string `gorm:"column:email;comment:电子邮箱" json:"email"`                                           // 电子邮箱
	Phonenum     string `gorm:"column:phonenum;comment:手机号码" json:"phonenum"`                                     // 手机号码
	Ismanager    int32  `gorm:"column:ismanager;not null;default:1;comment:是否为管理者 0==管理者 1==员工" json:"ismanager"` // 是否为管理者 0==管理者 1==员工
	Isystem      int32  `gorm:"column:isystem;not null;comment:是否系统自带数据" json:"isystem"`                          // 是否系统自带数据
	Status       int32  `gorm:"column:status;comment:状态，0正常，2封禁" json:"status"`                                   // 状态，0正常，2封禁
	Description  string `gorm:"column:description;comment:用户描述信息" json:"description"`                             // 用户描述信息
	Remark       string `gorm:"column:remark;comment:备注" json:"remark"`                                           // 备注
	WeixinOpenID string `gorm:"column:weixin_open_id;comment:微信绑定" json:"weixinOpenId"`                           // 微信绑定
	TenantID     int64  `gorm:"column:tenant_id;comment:租户id" json:"tenantId"`                                    // 租户id
	DeleteFlag   string `gorm:"column:delete_flag;comment:删除标记，0未删除，1删除" json:"deleteFlag"`                       // 删除标记，0未删除，1删除
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
