// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSerialNumber = "jsh_serial_number"

// SerialNumber 序列号表
type SerialNumber struct {
	ID           int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键" json:"id"` // 主键
	MaterialID   int64     `gorm:"column:material_id;comment:产品表id" json:"materialId"`           // 产品表id
	DepotID      int64     `gorm:"column:depot_id;comment:仓库id" json:"depotId"`                  // 仓库id
	SerialNumber string    `gorm:"column:serial_number;comment:序列号" json:"serialNumber"`         // 序列号
	IsSell       string    `gorm:"column:is_sell;comment:是否卖出，0未卖出，1卖出" json:"isSell"`           // 是否卖出，0未卖出，1卖出
	InPrice      float64   `gorm:"column:in_price;comment:入库单价" json:"inPrice"`                  // 入库单价
	Remark       string    `gorm:"column:remark;comment:备注" json:"remark"`                       // 备注
	CreateTime   time.Time `gorm:"column:create_time;comment:创建时间" json:"createTime"`            // 创建时间
	Creator      int64     `gorm:"column:creator;comment:创建人" json:"creator"`                    // 创建人
	UpdateTime   time.Time `gorm:"column:update_time;comment:更新时间" json:"updateTime"`            // 更新时间
	Updater      int64     `gorm:"column:updater;comment:更新人" json:"updater"`                    // 更新人
	InBillNo     string    `gorm:"column:in_bill_no;comment:入库单号" json:"inBillNo"`               // 入库单号
	OutBillNo    string    `gorm:"column:out_bill_no;comment:出库单号" json:"outBillNo"`             // 出库单号
	TenantID     int64     `gorm:"column:tenant_id;comment:租户id" json:"tenantId"`                // 租户id
	DeleteFlag   string    `gorm:"column:delete_flag;comment:删除标记，0未删除，1删除" json:"deleteFlag"`   // 删除标记，0未删除，1删除
}

// TableName SerialNumber's table name
func (*SerialNumber) TableName() string {
	return TableNameSerialNumber
}
