// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameFunction = "jsh_function"

// Function 功能模块表
type Function struct {
	ID           int64   `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键" json:"id"` // 主键
	Number       string  `gorm:"column:number;comment:编号" json:"number"`                       // 编号
	Name         string  `gorm:"column:name;comment:名称" json:"name"`                           // 名称
	ParentNumber string  `gorm:"column:parent_number;comment:上级编号" json:"parentNumber"`        // 上级编号
	URL          string  `gorm:"column:url;comment:链接" json:"url"`                             // 链接
	Component    string  `gorm:"column:component;comment:组件" json:"component"`                 // 组件
	State        []uint8 `gorm:"column:state;comment:收缩" json:"state"`                         // 收缩
	Sort         string  `gorm:"column:sort;comment:排序" json:"sort"`                           // 排序
	Enabled      []uint8 `gorm:"column:enabled;comment:启用" json:"enabled"`                     // 启用
	Type         string  `gorm:"column:type;comment:类型" json:"type"`                           // 类型
	PushBtn      string  `gorm:"column:push_btn;comment:功能按钮" json:"pushBtn"`                  // 功能按钮
	Icon         string  `gorm:"column:icon;comment:图标" json:"icon"`                           // 图标
	DeleteFlag   string  `gorm:"column:delete_flag;comment:删除标记，0未删除，1删除" json:"deleteFlag"`   // 删除标记，0未删除，1删除
}

// TableName Function's table name
func (*Function) TableName() string {
	return TableNameFunction
}
