// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNamePlatform_config = "jsh_platform_config"

// Platform_config 平台参数
type Platform_config struct {
	ID              int64  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	PlatformKey     string `gorm:"column:platform_key;comment:关键词" json:"platformKey"`            // 关键词
	PlatformKeyInfo string `gorm:"column:platform_key_info;comment:关键词名称" json:"platformKeyInfo"` // 关键词名称
	PlatformValue   string `gorm:"column:platform_value;comment:值" json:"platformValue"`          // 值
}

// TableName Platform_config's table name
func (*Platform_config) TableName() string {
	return TableNamePlatform_config
}
