// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTenant = "jsh_tenant"

// Tenant 租户
type Tenant struct {
	ID           int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键" json:"id"`     // 主键
	TenantID     int64     `gorm:"column:tenant_id;comment:用户id" json:"tenantId"`                    // 用户id
	LoginName    string    `gorm:"column:login_name;comment:登录名" json:"loginName"`                   // 登录名
	UserNumLimit int32     `gorm:"column:user_num_limit;comment:用户数量限制" json:"userNumLimit"`         // 用户数量限制
	Type         string    `gorm:"column:type;comment:租户类型，0免费租户，1付费租户" json:"type"`                 // 租户类型，0免费租户，1付费租户
	Enabled      []uint8   `gorm:"column:enabled;default:b'1';comment:启用 0-禁用  1-启用" json:"enabled"` // 启用 0-禁用  1-启用
	CreateTime   time.Time `gorm:"column:create_time;comment:创建时间" json:"createTime"`                // 创建时间
	ExpireTime   time.Time `gorm:"column:expire_time;comment:到期时间" json:"expireTime"`                // 到期时间
	Remark       string    `gorm:"column:remark;comment:备注" json:"remark"`                           // 备注
	DeleteFlag   string    `gorm:"column:delete_flag;comment:删除标记，0未删除，1删除" json:"deleteFlag"`       // 删除标记，0未删除，1删除
}

// TableName Tenant's table name
func (*Tenant) TableName() string {
	return TableNameTenant
}
