// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameIn_out_item = "jsh_in_out_item"

// In_out_item 收支项目
type In_out_item struct {
	ID         int64   `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键" json:"id"` // 主键
	Name       string  `gorm:"column:name;comment:名称" json:"name"`                           // 名称
	Type       string  `gorm:"column:type;comment:类型" json:"type"`                           // 类型
	Remark     string  `gorm:"column:remark;comment:备注" json:"remark"`                       // 备注
	Enabled    []uint8 `gorm:"column:enabled;comment:启用" json:"enabled"`                     // 启用
	Sort       string  `gorm:"column:sort;comment:排序" json:"sort"`                           // 排序
	TenantID   int64   `gorm:"column:tenant_id;comment:租户id" json:"tenantId"`                // 租户id
	DeleteFlag string  `gorm:"column:delete_flag;comment:删除标记，0未删除，1删除" json:"deleteFlag"`   // 删除标记，0未删除，1删除
}

// TableName In_out_item's table name
func (*In_out_item) TableName() string {
	return TableNameIn_out_item
}
