// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameAccount_item = "jsh_account_item"

// Account_item 财务子表
type Account_item struct {
	ID          int64   `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键" json:"id"` // 主键
	HeaderID    int64   `gorm:"column:header_id;not null;comment:表头Id" json:"headerId"`       // 表头Id
	AccountID   int64   `gorm:"column:account_id;comment:账户Id" json:"accountId"`              // 账户Id
	InOutItemID int64   `gorm:"column:in_out_item_id;comment:收支项目Id" json:"inOutItemId"`      // 收支项目Id
	BillID      int64   `gorm:"column:bill_id;comment:单据id" json:"billId"`                    // 单据id
	NeedDebt    float64 `gorm:"column:need_debt;comment:应收欠款" json:"needDebt"`                // 应收欠款
	FinishDebt  float64 `gorm:"column:finish_debt;comment:已收欠款" json:"finishDebt"`            // 已收欠款
	EachAmount  float64 `gorm:"column:each_amount;comment:单项金额" json:"eachAmount"`            // 单项金额
	Remark      string  `gorm:"column:remark;comment:单据备注" json:"remark"`                     // 单据备注
	TenantID    int64   `gorm:"column:tenant_id;comment:租户id" json:"tenantId"`                // 租户id
	DeleteFlag  string  `gorm:"column:delete_flag;comment:删除标记，0未删除，1删除" json:"deleteFlag"`   // 删除标记，0未删除，1删除
}

// TableName Account_item's table name
func (*Account_item) TableName() string {
	return TableNameAccount_item
}
