// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameSystem_config = "jsh_system_config"

// System_config 系统参数
type System_config struct {
	ID                      int64  `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键" json:"id"`                                 // 主键
	CompanyName             string `gorm:"column:company_name;comment:公司名称" json:"companyName"`                                          // 公司名称
	CompanyContacts         string `gorm:"column:company_contacts;comment:公司联系人" json:"companyContacts"`                                 // 公司联系人
	CompanyAddress          string `gorm:"column:company_address;comment:公司地址" json:"companyAddress"`                                    // 公司地址
	CompanyTel              string `gorm:"column:company_tel;comment:公司电话" json:"companyTel"`                                            // 公司电话
	CompanyFax              string `gorm:"column:company_fax;comment:公司传真" json:"companyFax"`                                            // 公司传真
	CompanyPostCode         string `gorm:"column:company_post_code;comment:公司邮编" json:"companyPostCode"`                                 // 公司邮编
	SaleAgreement           string `gorm:"column:sale_agreement;comment:销售协议" json:"saleAgreement"`                                      // 销售协议
	DepotFlag               string `gorm:"column:depot_flag;comment:仓库启用标记，0未启用，1启用" json:"depotFlag"`                                   // 仓库启用标记，0未启用，1启用
	CustomerFlag            string `gorm:"column:customer_flag;comment:客户启用标记，0未启用，1启用" json:"customerFlag"`                             // 客户启用标记，0未启用，1启用
	MinusStockFlag          string `gorm:"column:minus_stock_flag;comment:负库存启用标记，0未启用，1启用" json:"minusStockFlag"`                       // 负库存启用标记，0未启用，1启用
	PurchaseBySaleFlag      string `gorm:"column:purchase_by_sale_flag;comment:以销定购启用标记，0未启用，1启用" json:"purchaseBySaleFlag"`             // 以销定购启用标记，0未启用，1启用
	MultiLevelApprovalFlag  string `gorm:"column:multi_level_approval_flag;comment:多级审核启用标记，0未启用，1启用" json:"multiLevelApprovalFlag"`     // 多级审核启用标记，0未启用，1启用
	MultiBillType           string `gorm:"column:multi_bill_type;comment:流程类型，可多选" json:"multiBillType"`                                 // 流程类型，可多选
	ForceApprovalFlag       string `gorm:"column:force_approval_flag;comment:强审核启用标记，0未启用，1启用" json:"forceApprovalFlag"`                 // 强审核启用标记，0未启用，1启用
	UpdateUnitPriceFlag     string `gorm:"column:update_unit_price_flag;default:1;comment:更新单价启用标记，0未启用，1启用" json:"updateUnitPriceFlag"` // 更新单价启用标记，0未启用，1启用
	OverLinkBillFlag        string `gorm:"column:over_link_bill_flag;comment:超出关联单据启用标记，0未启用，1启用" json:"overLinkBillFlag"`               // 超出关联单据启用标记，0未启用，1启用
	InOutManageFlag         string `gorm:"column:in_out_manage_flag;comment:出入库管理启用标记，0未启用，1启用" json:"inOutManageFlag"`                  // 出入库管理启用标记，0未启用，1启用
	MultiAccountFlag        string `gorm:"column:multi_account_flag;comment:多账户启用标记，0未启用，1启用" json:"multiAccountFlag"`                   // 多账户启用标记，0未启用，1启用
	MoveAvgPriceFlag        string `gorm:"column:move_avg_price_flag;comment:移动平均价启用标记，0未启用，1启用" json:"moveAvgPriceFlag"`                // 移动平均价启用标记，0未启用，1启用
	AuditPrintFlag          string `gorm:"column:audit_print_flag;comment:先审核后打印启用标记，0未启用，1启用" json:"auditPrintFlag"`                    // 先审核后打印启用标记，0未启用，1启用
	ZeroChangeAmountFlag    string `gorm:"column:zero_change_amount_flag;comment:零收付款启用标记，0未启用，1启用" json:"zeroChangeAmountFlag"`         // 零收付款启用标记，0未启用，1启用
	CustomerStaticPriceFlag string `gorm:"column:customer_static_price_flag;comment:客户静态单价启用标记，0未启用，1启用" json:"customerStaticPriceFlag"` // 客户静态单价启用标记，0未启用，1启用
	MaterialPriceTaxFlag    string `gorm:"column:material_price_tax_flag;comment:商品价格含税启用标记，0未启用，1启用" json:"materialPriceTaxFlag"`       // 商品价格含税启用标记，0未启用，1启用
	TenantID                int64  `gorm:"column:tenant_id;comment:租户id" json:"tenantId"`                                                // 租户id
	DeleteFlag              string `gorm:"column:delete_flag;comment:删除标记，0未删除，1删除" json:"deleteFlag"`                                   // 删除标记，0未删除，1删除
}

// TableName System_config's table name
func (*System_config) TableName() string {
	return TableNameSystem_config
}
