// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameAccount = "jsh_account"

// Account 账户信息
type Account struct {
	ID            int64   `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键" json:"id"` // 主键
	Name          string  `gorm:"column:name;comment:名称" json:"name"`                           // 名称
	SerialNo      string  `gorm:"column:serial_no;comment:编号" json:"serialNo"`                  // 编号
	InitialAmount float64 `gorm:"column:initial_amount;comment:期初金额" json:"initialAmount"`      // 期初金额
	CurrentAmount float64 `gorm:"column:current_amount;comment:当前余额" json:"currentAmount"`      // 当前余额
	Remark        string  `gorm:"column:remark;comment:备注" json:"remark"`                       // 备注
	Enabled       []uint8 `gorm:"column:enabled;comment:启用" json:"enabled"`                     // 启用
	Sort          string  `gorm:"column:sort;comment:排序" json:"sort"`                           // 排序
	IsDefault     []uint8 `gorm:"column:is_default;comment:是否默认" json:"isDefault"`              // 是否默认
	TenantID      int64   `gorm:"column:tenant_id;comment:租户id" json:"tenantId"`                // 租户id
	DeleteFlag    string  `gorm:"column:delete_flag;comment:删除标记，0未删除，1删除" json:"deleteFlag"`   // 删除标记，0未删除，1删除
}

// TableName Account's table name
func (*Account) TableName() string {
	return TableNameAccount
}
