// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameUnit = "jsh_unit"

// Unit 多单位表
type Unit struct {
	ID             int64   `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键" json:"id"` // 主键
	Name           string  `gorm:"column:name;comment:名称，支持多单位" json:"name"`                     // 名称，支持多单位
	BasicUnit      string  `gorm:"column:basic_unit;comment:基础单位" json:"basicUnit"`              // 基础单位
	OtherUnit      string  `gorm:"column:other_unit;comment:副单位" json:"otherUnit"`               // 副单位
	OtherUnitTwo   string  `gorm:"column:other_unit_two;comment:副单位2" json:"otherUnitTwo"`       // 副单位2
	OtherUnitThree string  `gorm:"column:other_unit_three;comment:副单位3" json:"otherUnitThree"`   // 副单位3
	Ratio          float64 `gorm:"column:ratio;comment:比例" json:"ratio"`                         // 比例
	RatioTwo       float64 `gorm:"column:ratio_two;comment:比例2" json:"ratioTwo"`                 // 比例2
	RatioThree     float64 `gorm:"column:ratio_three;comment:比例3" json:"ratioThree"`             // 比例3
	Enabled        []uint8 `gorm:"column:enabled;comment:启用" json:"enabled"`                     // 启用
	TenantID       int64   `gorm:"column:tenant_id;comment:租户id" json:"tenantId"`                // 租户id
	DeleteFlag     string  `gorm:"column:delete_flag;comment:删除标记，0未删除，1删除" json:"deleteFlag"`   // 删除标记，0未删除，1删除
}

// TableName Unit's table name
func (*Unit) TableName() string {
	return TableNameUnit
}
