// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameLog = "jsh_log"

// Log 操作日志
type Log struct {
	ID         int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键" json:"id"` // 主键
	UserID     int64     `gorm:"column:user_id;comment:用户id" json:"userId"`                    // 用户id
	Operation  string    `gorm:"column:operation;comment:操作模块名称" json:"operation"`             // 操作模块名称
	ClientIP   string    `gorm:"column:client_ip;comment:客户端IP" json:"clientIp"`               // 客户端IP
	CreateTime time.Time `gorm:"column:create_time;comment:创建时间" json:"createTime"`            // 创建时间
	Status     int32     `gorm:"column:status;comment:操作状态 0==成功，1==失败" json:"status"`         // 操作状态 0==成功，1==失败
	Content    string    `gorm:"column:content;comment:详情" json:"content"`                     // 详情
	TenantID   int64     `gorm:"column:tenant_id;comment:租户id" json:"tenantId"`                // 租户id
}

// TableName Log's table name
func (*Log) TableName() string {
	return TableNameLog
}
