// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameMaterial_initial_stock = "jsh_material_initial_stock"

// Material_initial_stock 产品初始库存
type Material_initial_stock struct {
	ID            int64   `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键" json:"id"` // 主键
	MaterialID    int64   `gorm:"column:material_id;comment:产品id" json:"materialId"`            // 产品id
	DepotID       int64   `gorm:"column:depot_id;comment:仓库id" json:"depotId"`                  // 仓库id
	Number        float64 `gorm:"column:number;comment:初始库存数量" json:"number"`                   // 初始库存数量
	LowSafeStock  float64 `gorm:"column:low_safe_stock;comment:最低库存数量" json:"lowSafeStock"`     // 最低库存数量
	HighSafeStock float64 `gorm:"column:high_safe_stock;comment:最高库存数量" json:"highSafeStock"`   // 最高库存数量
	TenantID      int64   `gorm:"column:tenant_id;comment:租户id" json:"tenantId"`                // 租户id
	DeleteFlag    string  `gorm:"column:delete_flag;comment:删除标记，0未删除，1删除" json:"deleteFlag"`   // 删除标记，0未删除，1删除
}

// TableName Material_initial_stock's table name
func (*Material_initial_stock) TableName() string {
	return TableNameMaterial_initial_stock
}
