// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameSupplier = "jsh_supplier"

// Supplier 供应商/客户信息表
type Supplier struct {
	ID            int64   `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键" json:"id"`    // 主键
	Supplier      string  `gorm:"column:supplier;not null;comment:供应商名称" json:"supplier"`          // 供应商名称
	Contacts      string  `gorm:"column:contacts;comment:联系人" json:"contacts"`                     // 联系人
	PhoneNum      string  `gorm:"column:phone_num;comment:联系电话" json:"phoneNum"`                   // 联系电话
	Email         string  `gorm:"column:email;comment:电子邮箱" json:"email"`                          // 电子邮箱
	Description   string  `gorm:"column:description;comment:备注" json:"description"`                // 备注
	Isystem       int32   `gorm:"column:isystem;comment:是否系统自带 0==系统 1==非系统" json:"isystem"`       // 是否系统自带 0==系统 1==非系统
	Type          string  `gorm:"column:type;comment:类型" json:"type"`                              // 类型
	Enabled       []uint8 `gorm:"column:enabled;comment:启用" json:"enabled"`                        // 启用
	AdvanceIn     float64 `gorm:"column:advance_in;default:0.000000;comment:预收款" json:"advanceIn"` // 预收款
	BeginNeedGet  float64 `gorm:"column:begin_need_get;comment:期初应收" json:"beginNeedGet"`          // 期初应收
	BeginNeedPay  float64 `gorm:"column:begin_need_pay;comment:期初应付" json:"beginNeedPay"`          // 期初应付
	AllNeedGet    float64 `gorm:"column:all_need_get;comment:累计应收" json:"allNeedGet"`              // 累计应收
	AllNeedPay    float64 `gorm:"column:all_need_pay;comment:累计应付" json:"allNeedPay"`              // 累计应付
	Fax           string  `gorm:"column:fax;comment:传真" json:"fax"`                                // 传真
	Telephone     string  `gorm:"column:telephone;comment:手机" json:"telephone"`                    // 手机
	Address       string  `gorm:"column:address;comment:地址" json:"address"`                        // 地址
	TaxNum        string  `gorm:"column:tax_num;comment:纳税人识别号" json:"taxNum"`                     // 纳税人识别号
	BankName      string  `gorm:"column:bank_name;comment:开户行" json:"bankName"`                    // 开户行
	AccountNumber string  `gorm:"column:account_number;comment:账号" json:"accountNumber"`           // 账号
	TaxRate       float64 `gorm:"column:tax_rate;comment:税率" json:"taxRate"`                       // 税率
	Sort          string  `gorm:"column:sort;comment:排序" json:"sort"`                              // 排序
	Creator       int64   `gorm:"column:creator;comment:操作员" json:"creator"`                       // 操作员
	TenantID      int64   `gorm:"column:tenant_id;comment:租户id" json:"tenantId"`                   // 租户id
	DeleteFlag    string  `gorm:"column:delete_flag;comment:删除标记，0未删除，1删除" json:"deleteFlag"`      // 删除标记，0未删除，1删除
}

// TableName Supplier's table name
func (*Supplier) TableName() string {
	return TableNameSupplier
}
