// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNamePerson = "jsh_person"

// Person 经手人表
type Person struct {
	ID         int64   `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键" json:"id"` // 主键
	Type       string  `gorm:"column:type;comment:类型" json:"type"`                           // 类型
	Name       string  `gorm:"column:name;comment:姓名" json:"name"`                           // 姓名
	Enabled    []uint8 `gorm:"column:enabled;comment:启用" json:"enabled"`                     // 启用
	Sort       string  `gorm:"column:sort;comment:排序" json:"sort"`                           // 排序
	TenantID   int64   `gorm:"column:tenant_id;comment:租户id" json:"tenantId"`                // 租户id
	DeleteFlag string  `gorm:"column:delete_flag;comment:删除标记，0未删除，1删除" json:"deleteFlag"`   // 删除标记，0未删除，1删除
}

// TableName Person's table name
func (*Person) TableName() string {
	return TableNamePerson
}
