// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameRole = "jsh_role"

// Role 角色表
type Role struct {
	ID          int64   `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键" json:"id"`              // 主键
	Name        string  `gorm:"column:name;comment:名称" json:"name"`                                        // 名称
	Type        string  `gorm:"column:type;comment:类型" json:"type"`                                        // 类型
	PriceLimit  string  `gorm:"column:price_limit;comment:价格屏蔽 1-屏蔽采购价 2-屏蔽零售价 3-屏蔽销售价" json:"priceLimit"` // 价格屏蔽 1-屏蔽采购价 2-屏蔽零售价 3-屏蔽销售价
	Value       string  `gorm:"column:value;comment:值" json:"value"`                                       // 值
	Description string  `gorm:"column:description;comment:描述" json:"description"`                          // 描述
	Enabled     []uint8 `gorm:"column:enabled;comment:启用" json:"enabled"`                                  // 启用
	Sort        string  `gorm:"column:sort;comment:排序" json:"sort"`                                        // 排序
	TenantID    int64   `gorm:"column:tenant_id;comment:租户id" json:"tenantId"`                             // 租户id
	DeleteFlag  string  `gorm:"column:delete_flag;comment:删除标记，0未删除，1删除" json:"deleteFlag"`                // 删除标记，0未删除，1删除
}

// TableName Role's table name
func (*Role) TableName() string {
	return TableNameRole
}
