// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameOrganization = "jsh_organization"

// Organization 部门表
type Organization struct {
	ID         int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键" json:"id"` // 主键
	OrgNo      string    `gorm:"column:org_no;comment:部门编号" json:"orgNo"`                      // 部门编号
	OrgAbr     string    `gorm:"column:org_abr;comment:部门简称" json:"orgAbr"`                    // 部门简称
	ParentID   int64     `gorm:"column:parent_id;comment:父部门id" json:"parentId"`               // 父部门id
	Sort       string    `gorm:"column:sort;comment:部门显示顺序" json:"sort"`                       // 部门显示顺序
	Remark     string    `gorm:"column:remark;comment:备注" json:"remark"`                       // 备注
	CreateTime time.Time `gorm:"column:create_time;comment:创建时间" json:"createTime"`            // 创建时间
	UpdateTime time.Time `gorm:"column:update_time;comment:更新时间" json:"updateTime"`            // 更新时间
	TenantID   int64     `gorm:"column:tenant_id;comment:租户id" json:"tenantId"`                // 租户id
	DeleteFlag string    `gorm:"column:delete_flag;comment:删除标记，0未删除，1删除" json:"deleteFlag"`   // 删除标记，0未删除，1删除
}

// TableName Organization's table name
func (*Organization) TableName() string {
	return TableNameOrganization
}
