// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameMaterialCategory = "jsh_material_category"

// MaterialCategory 产品类型表
type MaterialCategory struct {
	ID            int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键" json:"id"` // 主键
	Name          string    `gorm:"column:name;comment:名称" json:"name"`                           // 名称
	CategoryLevel int32     `gorm:"column:category_level;comment:等级" json:"categoryLevel"`        // 等级
	ParentID      int64     `gorm:"column:parent_id;comment:上级id" json:"parentId"`                // 上级id
	Sort          string    `gorm:"column:sort;comment:显示顺序" json:"sort"`                         // 显示顺序
	SerialNo      string    `gorm:"column:serial_no;comment:编号" json:"serialNo"`                  // 编号
	Remark        string    `gorm:"column:remark;comment:备注" json:"remark"`                       // 备注
	CreateTime    time.Time `gorm:"column:create_time;comment:创建时间" json:"createTime"`            // 创建时间
	UpdateTime    time.Time `gorm:"column:update_time;comment:更新时间" json:"updateTime"`            // 更新时间
	TenantID      int64     `gorm:"column:tenant_id;comment:租户id" json:"tenantId"`                // 租户id
	DeleteFlag    string    `gorm:"column:delete_flag;comment:删除标记，0未删除，1删除" json:"deleteFlag"`   // 删除标记，0未删除，1删除
}

// TableName MaterialCategory's table name
func (*MaterialCategory) TableName() string {
	return TableNameMaterialCategory
}
