// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameDepot = "jsh_depot"

// Depot 仓库表
type Depot struct {
	ID          int64   `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键" json:"id"` // 主键
	Name        string  `gorm:"column:name;comment:仓库名称" json:"name"`                         // 仓库名称
	Address     string  `gorm:"column:address;comment:仓库地址" json:"address"`                   // 仓库地址
	Warehousing float64 `gorm:"column:warehousing;comment:仓储费" json:"warehousing"`            // 仓储费
	Truckage    float64 `gorm:"column:truckage;comment:搬运费" json:"truckage"`                  // 搬运费
	Type        int32   `gorm:"column:type;comment:类型" json:"type"`                           // 类型
	Sort        string  `gorm:"column:sort;comment:排序" json:"sort"`                           // 排序
	Remark      string  `gorm:"column:remark;comment:描述" json:"remark"`                       // 描述
	Principal   int64   `gorm:"column:principal;comment:负责人" json:"principal"`                // 负责人
	Enabled     []uint8 `gorm:"column:enabled;comment:启用" json:"enabled"`                     // 启用
	TenantID    int64   `gorm:"column:tenant_id;comment:租户id" json:"tenantId"`                // 租户id
	DeleteFlag  string  `gorm:"column:delete_Flag;comment:删除标记，0未删除，1删除" json:"deleteFlag"`   // 删除标记，0未删除，1删除
	IsDefault   []uint8 `gorm:"column:is_default;comment:是否默认" json:"isDefault"`              // 是否默认
}

// TableName Depot's table name
func (*Depot) TableName() string {
	return TableNameDepot
}
