// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameSequence = "jsh_sequence"

// Sequence 单据编号表
type Sequence struct {
	SeqName      string `gorm:"column:seq_name;primaryKey;comment:序列名称" json:"seqName"`                   // 序列名称
	MinValue     int64  `gorm:"column:min_value;not null;comment:最小值" json:"minValue"`                    // 最小值
	MaxValue     int64  `gorm:"column:max_value;not null;comment:最大值" json:"maxValue"`                    // 最大值
	CurrentVal   int64  `gorm:"column:current_val;not null;comment:当前值" json:"currentVal"`                // 当前值
	IncrementVal int32  `gorm:"column:increment_val;not null;default:1;comment:增长步数" json:"incrementVal"` // 增长步数
	Remark       string `gorm:"column:remark;comment:备注" json:"remark"`                                   // 备注
}

// TableName Sequence's table name
func (*Sequence) TableName() string {
	return TableNameSequence
}
