// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameMaterialExtend = "jsh_material_extend"

// MaterialExtend 产品价格扩展
type MaterialExtend struct {
	ID               int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键" json:"id"`           // 主键
	MaterialID       int64     `gorm:"column:material_id;comment:商品id" json:"materialId"`                      // 商品id
	BarCode          string    `gorm:"column:bar_code;comment:商品条码" json:"barCode"`                            // 商品条码
	CommodityUnit    string    `gorm:"column:commodity_unit;comment:商品单位" json:"commodityUnit"`                // 商品单位
	Sku              string    `gorm:"column:sku;comment:多属性" json:"sku"`                                      // 多属性
	PurchaseDecimal  float64   `gorm:"column:purchase_decimal;comment:采购价格" json:"purchaseDecimal"`            // 采购价格
	CommodityDecimal float64   `gorm:"column:commodity_decimal;comment:零售价格" json:"commodityDecimal"`          // 零售价格
	WholesaleDecimal float64   `gorm:"column:wholesale_decimal;comment:销售价格" json:"wholesaleDecimal"`          // 销售价格
	LowDecimal       float64   `gorm:"column:low_decimal;comment:最低售价" json:"lowDecimal"`                      // 最低售价
	DefaultFlag      string    `gorm:"column:default_flag;default:1;comment:是否为默认单位，1是，0否" json:"defaultFlag"` // 是否为默认单位，1是，0否
	CreateTime       time.Time `gorm:"column:create_time;comment:创建日期" json:"createTime"`                      // 创建日期
	CreateSerial     string    `gorm:"column:create_serial;comment:创建人编码" json:"createSerial"`                 // 创建人编码
	UpdateSerial     string    `gorm:"column:update_serial;comment:更新人编码" json:"updateSerial"`                 // 更新人编码
	UpdateTime       int64     `gorm:"column:update_time;comment:更新时间戳" json:"updateTime"`                     // 更新时间戳
	TenantID         int64     `gorm:"column:tenant_id;comment:租户id" json:"tenantId"`                          // 租户id
	DeleteFlag       string    `gorm:"column:delete_Flag;comment:删除标记，0未删除，1删除" json:"deleteFlag"`             // 删除标记，0未删除，1删除
}

// TableName MaterialExtend's table name
func (*MaterialExtend) TableName() string {
	return TableNameMaterialExtend
}
