// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAccount_head = "jsh_account_head"

// Account_head 财务主表
type Account_head struct {
	ID            int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键" json:"id"`       // 主键
	Type          string    `gorm:"column:type;comment:类型(支出/收入/收款/付款/转账)" json:"type"`                 // 类型(支出/收入/收款/付款/转账)
	OrganID       int64     `gorm:"column:organ_id;comment:单位Id(收款/付款单位)" json:"organId"`               // 单位Id(收款/付款单位)
	HandsPersonID int64     `gorm:"column:hands_person_id;comment:经手人id" json:"handsPersonId"`          // 经手人id
	Creator       int64     `gorm:"column:creator;comment:操作员" json:"creator"`                          // 操作员
	ChangeAmount  float64   `gorm:"column:change_amount;comment:变动金额(优惠/收款/付款/实付)" json:"changeAmount"` // 变动金额(优惠/收款/付款/实付)
	DiscountMoney float64   `gorm:"column:discount_money;comment:优惠金额" json:"discountMoney"`            // 优惠金额
	TotalPrice    float64   `gorm:"column:total_price;comment:合计金额" json:"totalPrice"`                  // 合计金额
	AccountID     int64     `gorm:"column:account_id;comment:账户(收款/付款)" json:"accountId"`               // 账户(收款/付款)
	BillNo        string    `gorm:"column:bill_no;comment:单据编号" json:"billNo"`                          // 单据编号
	BillTime      time.Time `gorm:"column:bill_time;comment:单据日期" json:"billTime"`                      // 单据日期
	Remark        string    `gorm:"column:remark;comment:备注" json:"remark"`                             // 备注
	FileName      string    `gorm:"column:file_name;comment:附件名称" json:"fileName"`                      // 附件名称
	Status        string    `gorm:"column:status;comment:状态，0未审核、1已审核、9审核中" json:"status"`              // 状态，0未审核、1已审核、9审核中
	Source        string    `gorm:"column:source;comment:单据来源，0-pc，1-手机" json:"source"`                 // 单据来源，0-pc，1-手机
	TenantID      int64     `gorm:"column:tenant_id;comment:租户id" json:"tenantId"`                      // 租户id
	DeleteFlag    string    `gorm:"column:delete_flag;comment:删除标记，0未删除，1删除" json:"deleteFlag"`         // 删除标记，0未删除，1删除
}

// TableName Account_head's table name
func (*Account_head) TableName() string {
	return TableNameAccount_head
}
